# Generated by Django 4.2 on 2023-09-27 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoCultura', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProprietarios', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=11)),
                ('contato', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Propriedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=40)),
                ('Microrregiao', models.CharField(max_length=40)),
                ('Cidade', models.CharField(max_length=40)),
                ('app', models.CharField(max_length=20)),
                ('rl', models.CharField(max_length=50)),
                ('rl_coordenadas', models.CharField(max_length=13)),
                ('tamanho_area', models.CharField(max_length=11)),
                ('Culturas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.culturas')),
                ('Proprietarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proprietarios')),
            ],
        ),
    ]
